### ISSUE TITLE
Visual corruption on the Dreamcast

### ISSUE THREAD

**Issue by azihassan** [diasurgical/devilutionx-asset-optimizer#13]
Hello, after switching to unpacked MPQs I noticed that it produces this distortion:

![image](https://github.com/user-attachments/assets/40ab82f0-f325-4810-b0b3-6ad96aca618b)

Version 1.5.1 works as expected, but the commit where devilutionx-graphics-tools is bumped is what introduces the issue. Specifically, commit [5f260010b0af26e9c453931f42edcb02ce894a16](https://github.com/diasurgical/devilutionx-graphics-tools/commit/5f260010b0af26e9c453931f42edcb02ce894a16) segfaults with diabdat.mpq, and commit https://github.com/diasurgical/devilutionx-graphics-tools/commit/ae39773dc2932b82328507bb51f79fa13b561ec0 unpacks it but causes the bug above. More details here: https://github.com/azihassan/devilutionX/issues/15#issuecomment-2433980397

Does this happen on the other platforms?

**Comment by StephenCWills** [comment]
Tried this on Windows x64.
Using commit d354283 to unpack
Which uses https://github.com/diasurgical/devilutionx-graphics-tools/commit/ae39773dc2932b82328507bb51f79fa13b561ec0
And loaded into https://github.com/diasurgical/devilutionX/commit/bd1881957b544d3e40c958a8d389120c19d1a1ba

Everything looks okay to me.

![image](https://github.com/user-attachments/assets/0f58749f-de13-46de-8952-d37dc0c8e703)

Any chance you can try loading the CLX file into https://github.com/diasurgical/d1-graphics-tool/commit/6c57fd8094ea9c109c791e57407633b5fe18f193 to see if it has similar problems?

EDIT: I should have mentioned in case you didn't know, the file to open is `ui_art\logo.clx`.

**Comment by glebm** [comment]
Have you rebased the Dreamcast branch recently? Support for smaller-header CLX files was only added to DevilutionX recently.

**Comment by azihassan** [comment]
Thanks guys, I'll try these suggestions.

>Have you rebased the Dreamcast branch recently?

Actually no, the last update was three weeks ago. I'm just now realizing that it's 24 commits behind

**Comment by azihassan** [comment]
Sorry guys it was a false alarm! Updating the fork fixed the issue, it was missing the relevant commits from upstream. Thanks for the help :pray:
