### ISSUE TITLE
Make installation simple

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionx-asset-optimizer#2]
Python requires a bit to get up and running, it would be good if we can convert this to something that people just drop in a folder and double click. Or alternativ a GUI that open a window for you to drag and drop the MPQ in to.

**Comment by glebm** [comment]
You can simply drag and drop the MPQ onto the python file. However, it does require python, smpq, and *2clx to be installed

**Comment by AJenbo** [comment]
Back when I used Windows I remember Vampire the Masquerade exploding because I had installed Python on my computer...

I think it has been well established that humans are not good at managing dependencies. For example Steam will do so on first launch of a new game.

**Comment by glebm** [comment]
Yeah, probably the ideal scenario is a single statically linked C++ binary that calls libmpq to extract the files and *2clx and lame libraries to convert the data directly.
